# Change these first
owner: dragon-yuan # Your GitHub username
repo: dragon-upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: DragonYuan Website
    url: https://www.dragon-yuan.me
